greenthumb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    
    path('about/', views.about, name='about'),
    
    path('gardens/', views.gardens_index, name='index'),
    
    path('gardens/<int:garden_id>/', views.journal, name='journal'),
    
    path('gardens/create/', views.GardenCreate.as_view(), name='gardens_create'),
    
    path('gardens/<int:pk>/update/', views.GardenUpdate.as_view(), name='gardens_update'),
    
    path('gardens/<int:pk>/delete/', views.GardenDelete.as_view(), name='gardens_delete'),
    
    path('gardens/<int:garden_id>/add_plant/', views.add_plant, name='add_plant'),
    
    path('gardens/<int:pk>/update', views.PlantUpdate.as_view(), name='edit_plant'),
    
    path('gardens/<int:pk>/delete', views.PlantDelete.as_view(), name='delete_plant'),
    
    path('accounts/signup/', views.signup, name='signup'),
    
    # path('gardens/<int:garden_id>/add_entry', views.add_entry, name='add_entry'),
    
]

main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date
from django.contrib.auth.models import User

LIGHT = (
    ('S', 'Full Sun'),
    ('PS', 'Partial Sun'),
    ('FS', 'Full Shade'),
)

# Create your models here.
class Garden(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField()
    date = models.DateField()
    journal = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('journal', kwargs={'garden_id': self.id})
    
    
class Care_Guide(models.Model):
    zone = models.CharField()
    food = models.CharField(max_length=100)
    light = models.CharField(choices=LIGHT, default=LIGHT[0][0])
    water = models.CharField()
    companions = models.CharField()
    notes = models.CharField()
    
    
    def __str__(self):
        return self.name
    
    
    
class Plant(models.Model):
    name = models.CharField(max_length=100)
    date = models.DateField()
    variety = models.CharField(max_length=100)
    seeds_sown = models.IntegerField(null=True)
    germination = models.DateField(null=True)
    garden = models.ForeignKey(Garden, on_delete=models.CASCADE)
    
    
    def __str__(self):
        return f"{self.get_variety_display()} on {self.date}"
    
    def get_absolute_url(self):
        return reverse('journal', kwargs={'garden_id': self.id})
    
    class Meta:
        ordering = ['-date']

main_app/forms.py
from django.forms import ModelForm 
from .models import *

class PlantForm(ModelForm):
    class Meta:
        model = Plant
        fields = ['name','date','variety']
        
class JournalForm(ModelForm):
    class Meta:
        model = Garden
        fields = ['date', 'journal']        
        

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic import CreateView, UpdateView, DeleteView, ListView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import *
from .forms import *

# Create your views here.
@login_required
def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

@login_required
def gardens_index(request):
    gardens = Garden.objects.filter(user=request.user)
    return render(request, 'gardens/index.html',{
        'gardens': gardens
    })
@login_required
def journal(request, garden_id):
    garden = Garden.objects.get(id=garden_id)
    plant_form = PlantForm()
    return render(request, 'gardens/journal.html', {
       'garden': garden,
       'plant_form': plant_form,
    })
    

# def add_entry(request, garden_id):
#     form = JournalForm(request.POST)
#     if form.is_valid():
#         new_entry = form.save(commit=False)
#         new_entry.garden_id = garden_id
#         new_entry.save()
#     return redirect('journal', garden_id=garden_id)
    
@login_required
def add_plant(request, garden_id):
    form = PlantForm(request.POST)
    if form.is_valid():
        new_plant = form.save(commit=False)
        new_plant.garden_id = garden_id
        new_plant.save()
    return redirect('journal', garden_id=garden_id)

def signup(request):
    error_message = ''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request,user)
            return redirect('index')
        else:
            error_message = 'Invalid sign up - try again'
    form = UserCreationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'registration/signup.html', context)
    

class GardenCreate(LoginRequiredMixin, CreateView):
    model = Garden
    fields = ['name', 'description', 'date', 'journal']
    
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)
    
class GardenUpdate(LoginRequiredMixin, UpdateView):
    model = Garden
    fields = ['description', 'date', 'journal']

class GardenDelete(LoginRequiredMixin, DeleteView):
    model = Garden
    success_url = '/gardens'
    
class PlantUpdate(LoginRequiredMixin, UpdateView):
    model = Plant
    fields = ['name','date','variety']
    success_url = '/gardens'

class PlantDelete(LoginRequiredMixin, DeleteView):
    model = Plant
    success_url = '/garden/<int:garden_id>'
    
class JournalList(ListView):
    model = Garden
    fields = ['date', 'journal']
    template_name = "gardens/journal.html"

main_app/templates/about.html
{% extends 'base.html' %}
{% block content%}

<div class="h1-card">
    <div class="h1-card-content">
        <div>
            <span>
                <h1>Green Thumb!</h1>
            </span>
            <span class="about-sub">
                <h5>The Garden Buddy</h5>
            </span>
        </div>
    </div>
</div>

<hr>
<p>With Green Thumb! Your Garden Buddy, you'll be abe to organize your garden space and monitor its progress </p>

{% endblock %}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Green Thumb</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

</head>

<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li>
            <div class="left">
              <span><a href="{% url 'home' %}" class="left brand-logo-top">Green Thumb!</span></a></span></span>
              <span class="left brand-logo-bottom">
                <h6>Your Garden Buddy</h6>
              </span>
            </div>
          </li>
        </ul>
        <ul class="right">
          <li><a href="{% url 'about' %}">About</a></li>
          {% if user.is_authenticated %}
          <li><a href="{% url 'index' %}">View all Gardens</a></li>
          <li><a href="{% url 'logout' %}">Log Out</a></li>
          {% else %}
          <li><a href="{% url 'signup' %}">Sign Up</a></li>
          <li><a href="{% url 'login' %}">Log In</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="color">All Rights Reserved, &copy; 2023 Green Thumb &nbsp;</div>
  </footer>
</body>

</html>

main_app/templates/gardens/index.html
{% extends 'base.html' %}
{% block content %}

<div class="h1-card">
    <div class="h1-card-content">
        <h1>Garden List</h1>
    </div>
</div>

<span>
    <ul>
        <li><button class="add-btn"><a color="white" href="{% url 'gardens_create' %}">Add Garden</a></button></li>
    </ul>
</span>

{% for garden in gardens %}
<div class="card">
    <div class="card-content">
        <span class="card-title">{{ garden.name }}</span>
        <p>Description: {{ garden.description }}</p>
        <p>Date: {{ garden.date }}</p>
        <p><a href="{% url 'journal' garden.id %}">Journal</a></p>
    </div>

    <div class="card-action">
        <a href="{% url 'gardens_update' garden.id %}">Edit</a>
        <a href="{% url 'gardens_delete' garden.id %}">Delete</a>
    </div>

</div>
{% endfor %}


{% endblock %}

main_app/templates/gardens/journal.html
{% extends 'base.html'%}
{% block content %}


<h1 class="">{{ garden.name }} Journal</h1>
  
<div class="card">
    <div class="card-content">
        <p>Description: {{ garden.description|linebreaks }}</p>
    </div>
</div>

<div class="card">
    <div class="card-content">
        <h5 id="entry-title">Journal Entries</h5>
        <div class="entry">
            <p id="entry-date">{{ garden.date }}: </p>
            <p id="entry-journal">{{ garden.journal }}
            </p>
        </div>
    </div>
</div>

<div class="card">
    <div class="card-content">
        <form action="" method="POST">
            {% csrf_token %}
            {{ journal_form.as_table }}
            <label for="journal_entry">New Journal Entry: </label>
            <input></input>
            <textarea id="add-entry"></textarea>
            <input type="submit" class="btn" value="Add Entry">
        </form>

        <tbody>
            {% for journal in garden.journal_set.all %}
            <tr>
                <td>{{garden.date}}</td>
                <td>{{garden.journal}}</td>

            </tr>
            <div class="card-action">
                <a href="{% url 'edit_plant' plant.id %}">Edit</a>
                <a href="{% url 'delete_plant' plant.id %}">Delete</a>
            </div>
            {% endfor %}
        </tbody>
        </table>

    </div>
</div>



<div class="card">
    <div class="card-content">
        <div class="col s6">

            <form action="{% url 'add_plant' garden.id %}" method="POST">
                {% csrf_token %}
                {{ plant_form.as_p }}
                <input type="submit" class="btn" value="Add Plant">
            </form>

            <table class="striped">
                <thead>
                    <tr>
                        <th>Date</th>
                        <th>Name</th>
                        <th>Variety</th>
                    </tr>
                </thead>

                <tbody>
                    {% for plant in garden.plant_set.all %}
                    <tr>
                        <td>{{plant.date}}</td>
                        <td>{{plant.name}}</td>
                        <td>{{plant.variety}}</td>
                        <td><a href="{% url 'edit_plant' plant.id %}">Edit</a></td>
                        <td> <a href="{% url 'delete_plant' plant.id %}">Delete</a></td>

                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

<script>
    const dateEl = document.getElementById('id_date')
    M.Datepicker.init(dateEl, {
        format: 'yyyy-mm-dd',
        defaultDate: new Date(),
        setDefaultDate: true,
        autoClose: true
    })

</script>

{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}
{% block content%}

<div class="home">
    <div class="h1-card">
        <div class="h1-card-content">
            <h1>Welcome to <br> Green Thumb! <br> <span></span></h1>
        </div>
    </div>

    <div class="home-msg">
        <h4>Happy Gardening</h4>
    </div>

    <div class="home-img">
        <img src="https://img.freepik.com/free-vector/person-s-green-thumb_1308-18854.jpg">
    </div>
</div>

{% endblock %}

main_app/templates/main_app/add_entry.html
{% extends 'base.html' %}
{% block content %}

{% if object %}
<h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
<h1>Add Garden</h1>
{% endif %}


<form action="" method="POST">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <input type="submit" value="Submit!" class="btn">
</form>


{% endblock %}

main_app/templates/main_app/garden_confirm_delete.html
{% extends 'base.html' %}
{% block content %}

<h1>Delete Garden</h1>

<h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes - Delete!" class="btn">
  <a href="{% url 'index' %}">Cancel</a>
</form>


{% endblock %}

main_app/templates/main_app/garden_form.html
{% extends 'base.html' %}
{% block content %}

{% if object %}
<h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
<h1>Add Garden</h1>
{% endif %}


<form action="" method="POST">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <input type="submit" value="Submit!" class="btn">
</form>


{% endblock %}

main_app/templates/main_app/plant_confirm_delete.html
{% extends 'base.html' %}
{% block content %}

<h1>Delete Plant</h1>

<h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes - Delete!" class="btn">
  <a href="{% url 'journal' plant.id %}">Cancel</a>
</form>


{% endblock %}

main_app/templates/main_app/plant_form.html
{% extends 'base.html' %}
{% block content %}

{% if object %}
<h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
<h1>Add Plant</h1>
{% endif %}


<form action="" method="POST">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <input type="submit" value="Submit!" class="btn">
</form>


{% endblock %}